### ISSUE TITLE
clEnqueueNDRangeKernel failed: mem object allocation failure

### ISSUE THREAD

**Issue by sburina** [reorder/momentum-getwork#1]
Hi!

Is there a way to solve this one:

PTSHasher:0-0 initialized on device: GeForce GTS 450 type: 4, vendor: NVIDIA Corporation, LE: 1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "./miner.py", line 259, in miner_thread
    miner.loop()
  File "./miner.py", line 254, in loop
    self.iterate()
  File "./miner.py", line 243, in iterate
    output = self.hasher.processMidstate(work['midstate'])
  File "/home/six/work/git/MMC/momentum-getwork/pts.py", line 80, in processMidstate
    return self.search(midstate)
  File "/home/six/work/git/MMC/momentum-getwork/pts.py", line 62, in search
    cl.enqueue_nd_range_kernel(self.queue, self.sha512_fill, (HASHES_NUM,), (self.sha512_fill_ws,))
MemoryError: clEnqueueNDRangeKernel failed: mem object allocation failure

Best regards!

**Comment by reorder** [comment]
Try adding RAM and/or allocating more swap on machine you run on. May help, but not guaranteed.

**Comment by sburina** [comment]
Turned out it's the lack of memory on the graphic card. It seems that 2GB is the required minimum.

**Comment by reorder** [comment]
It actually requires under 1G VRAM, but at least 512M of it should be in one piece. It is possible that the card cannot allocate continuous 512M even if it has 1G+ total.

**Comment by ziyush** [comment]
This issue is because you have not set virtual memory in your system, change default memory and it will work check this article how to do it https://coinpricetoday.com/crypto/memory-object-allocation-failure-monero-ethereum-mining-issue-solved/
